from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class SignalDirection(Enum):
    UP = "UP"
    DOWN = "DOWN"


@dataclass
class Signal:
    """trading signal generated by strategy"""

    coin: str
    direction: SignalDirection
    timestamp: datetime
    start_price: float  # price at window start
    current_price: float  # price when signal generated
    pct_change: float  # percentage change from start
    market_slug: str
    token_id: str  # token to buy (up or down)

    @property
    def edge(self) -> float:
        """estimated edge based on price movement"""
        return abs(self.pct_change)
