[build]
builder = "nixpacks"

[deploy]
startCommand = "uv run python main.py"
restartPolicyType = "always"

# collector service config
[[services]]
name = "collector"
[services.build]
builder = "dockerfile"
dockerfilePath = "collector/Dockerfile"
[services.deploy]
restartPolicyType = "always"
